import esbuild from "esbuild";
import { copy } from "esbuild-plugin-copy";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      "fs",
      "path",
      "crypto",
      "stream",
      "util",
      "events",
      "url",
      "http",
      "https",
      "os",
      "child_process",
      "buffer",
      "querystring",
      "net",
      "tls",
      "dns",
      "zlib",
      "readline",
      "repl",
      "vm",
      "assert",
      "console",
      "module",
      "process",
      "timers",
      "tty",
      "dgram",
      "cluster",
      "worker_threads",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
    plugins: [
      copy({
        resolveFrom: "cwd",
        assets: [
          {
            from: ["./manifest.json"],
            to: ["."],
          },
        ],
      }),
    ],
  })
  .catch(() => process.exit(1));
